services:
  db:
    container_name: parler_dev-db
    image: postgres:18.0
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chess_trainer_dev
    ports:
      - "5432:5432"
